👷 Add states of the App Runner to check

diff --git a/.github/workflows/deployment-to-dev.yml b/.github/workflows/deployment-to-dev.yml
--- a/.github/workflows/deployment-to-dev.yml
+++ b/.github/workflows/deployment-to-dev.yml
@@ -80,19 +80,32 @@ jobs:
     - name: Deploy to AWS App Runner
       id: deploy
       run: |
-        STATUS=$(aws apprunner describe-service --service-arn ${{ env.APP_RUNNER_SERVICE_ARN }} --query 'Service.Status' --output text)
-        if [ "$STATUS" == "PAUSED" ]; then
-          echo "Service is PAUSED. Resuming service..."
-          aws apprunner resume-service --service-arn ${{ env.APP_RUNNER_SERVICE_ARN }}
-          echo "Waiting for service to become active..."
-          aws apprunner wait service-running --service-arn ${{ env.APP_RUNNER_SERVICE_ARN }}
-          echo "Service is now RUNNING."
-        fi
+        SERVICE_ARN=${{ env.APP_RUNNER_SERVICE_ARN }}
+        STATUS=$(aws apprunner describe-service --service-arn $SERVICE_ARN --query 'Service.Status' --output text)
+        echo "Current App Runner service status is: $STATUS"
 
-        echo "Starting a new deployment..."
-        aws apprunner start-deployment --service-arn ${{ env.APP_RUNNER_SERVICE_ARN }}
-        echo "Waiting for the deployment to complete..."
-        aws apprunner wait service-stable --service-arn ${{ env.APP_RUNNER_SERVICE_ARN }} --region ${{ env.AWS_REGION }}
+        case $STATUS in
+          "PAUSED")
+            echo "Service is PAUSED. Resuming service..."
+            aws apprunner resume-service --service-arn $SERVICE_ARN
+            echo "Waiting for service to become active..."
+            aws apprunner wait service-running --service-arn $SERVICE_ARN
+            echo "Service is now RUNNING."
+            ;;
+          "CREATE_FAILED" | "UPDATE_FAILED" | "DELETE_FAILED")
+            echo "::error::Service is in a non-recoverable state: $STATUS."
+            echo "Please check the AWS App Runner console event logs, then delete and recreate the service."
+            exit 1
+            ;;
+          "RUNNING")
+            echo "Service is RUNNING. Proceeding with deployment."
+            ;;
+        esac
+
+        echo "Starting a new deployment for service $SERVICE_ARN..."
+        aws apprunner start-deployment --service-arn $SERVICE_ARN
+        echo "Waiting for the new deployment to become stable..."
+        aws apprunner wait service-stable --service-arn $SERVICE_ARN --region ${{ env.AWS_REGION }}
 
     - name: Send Success Message
       if: success()
